package com.yih.bt;


/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class BtClient {
    public static void main(String[] args) throws InterruptedException {


    }
}